---
name: Docker Hub Description Updates

env:
  DOCKERHUB_NAMESPACE: dfuchs

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - '.github/workflows/hub.yaml'
  workflow_dispatch:

jobs:
  update-hub-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Docker Hub description (alma)
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_NAMESPACE }}/did-alma
          short-description: ${{ github.event.repository.description }}

      - name: Update Docker Hub description (debian)
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_NAMESPACE }}/did-debian
          short-description: ${{ github.event.repository.description }}

      - name: Update Docker Hub description (ubuntu)
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_NAMESPACE }}/did-ubuntu
          short-description: ${{ github.event.repository.description }}
