---
name: Update Docker Hub Description

env:
  DOCKERHUB_NAMESPACE: dfuchs

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  update-hub-description:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_NAMESPACE }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update Docker Hub description (alma-9)
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: dfuchs/did-alma
          short-description: ${{ github.event.repository.description }}

      - name: Update Docker Hub description (alma-9)
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: dfuchs/did-debian
          short-description: ${{ github.event.repository.description }}

      - name: Update Docker Hub description (alma-9)
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: dfuchs/did-ubuntu
          short-description: ${{ github.event.repository.description }}
