---
name: Publish Docker Images

env:
  DOCKERHUB_NAMESPACE: dfuchs

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Which image(s) to build and publish'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - alma_8
          - alma_9
          - debian_11
          - debian_12
          - ubuntu_2204
          - ubuntu_2404

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro_name: alma
            distro_version: 8
          - distro_name: alma
            distro_version: 9
          - distro_name: debian
            distro_version: 11
          - distro_name: debian
            distro_version: 12
          - distro_name: ubuntu
            distro_version: 2204
          - distro_name: ubuntu
            distro_version: 2404
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_NAMESPACE }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish ${{ matrix.distro_name }}_${{ matrix.distro_version }}
        if: github.event.inputs.image == 'all' || github.event.inputs.image == 'all' || github.event.inputs.image == format('{0}_{1}', matrix.distro_name, matrix.distro_version)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.distro_name }}_${{ matrix.distro_version }}.Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_NAMESPACE }}/did-${{ matrix.distro_name }}:latest
          cache-from: type=gha,scope=${{ matrix.distro_name }}_${{ matrix.distro_version }}
